Repository callistoteam/schoolbot, pull requests merged in 2020-08, with the labels that each got.

#1 feat: file structure and test code
  .github/workflows/python-app.yml
  README.md
  requirements.txt
  schoolbot/__init__.py
  schoolbot/__main__.py
  schoolbot/bot.py
  schoolbot/cogs/events/__init__.py
  schoolbot/cogs/events/ready.py
  test/__init__.py
  test/test_load_extension.py
Labels: chore, docs, feature, test, to develop

#2 feat: file structure and test code, docs, build test
  .github/workflows/python-app.yml
  README.md
  requirements.txt
  schoolbot/__init__.py
  schoolbot/__main__.py
  schoolbot/bot.py
  schoolbot/cogs/events/__init__.py
  schoolbot/cogs/events/ready.py
  test/__init__.py
  test/test_load_extension.py
Labels: chore, docs, feature, fix, test, to staging

#3 fix: token must in __main__
  schoolbot/__main__.py
  schoolbot/bot.py
Labels: fix

#5 fix: cogs directory
  schoolbot/bot.py
Labels: fix

#7 Update 0.1.0
  .github/CODEOWNERS
  .github/workflows/python-app.yml
  Aptfile
  Procfile
  README.md
  requirements.txt
  runtime.txt
  schoolbot/__init__.py
  schoolbot/__main__.py
  schoolbot/bot.py
  schoolbot/cogs/events/__init__.py
  schoolbot/cogs/events/ready.py
  test/__init__.py
  test/test_load_extension.py
Labels: chore, feature, release, test

#8 style: apply code style
  schoolbot/cogs/events/__init__.py
  schoolbot/cogs/events/ready.py
  test/test_load_extension.py
Labels: hotfix

#13 feat: meal info
  .github/workflows/python-app.yml
  requirements.txt
  schoolbot/bot.py
  schoolbot/cogs/school/__init__.py
  schoolbot/cogs/school/meal.py
Labels: feature, to staging

#14 docs: add badge
  README.md
Labels: docs

#21 feat: iamschool article
  .github/workflows/python-app.yml
  install_dependency.py
  schoolbot/cogs/school/__init__.py
  schoolbot/cogs/school/article.py
Labels: feature, to staging

#22 deploy beta
  .github/workflows/python-app.yml
  install_dependency.py
  run.sh
  schoolbot/cogs/school/__init__.py
  schoolbot/cogs/school/article.py
Labels: QA

#26 feat: timetable
  .github/workflows/python-app.yml
  schoolbot/cogs/school/timetable.py
Labels: feature, to staging

#27 feat: help, fix: if info 200 raise unexpected error
  .github/workflows/python-app.yml
  install_dependency.py
  schoolbot/cogs/general/__init__.py
  schoolbot/cogs/general/help.py
  schoolbot/cogs/school/timetable.py
Labels: feature, fix, to staging

#29 deploy beta
  .github/workflows/python-app.yml
  README.md
  install_dependency.py
  schoolbot/cogs/general/__init__.py
  schoolbot/cogs/general/help.py
  schoolbot/cogs/school/timetable.py
Labels: QA

#30 Ready to release 1.0.0
  schoolbot/__init__.py
  schoolbot/bot.py
  schoolbot/cogs/events/ready.py
Labels: feature, style, to staging

#31 deploy beta
  schoolbot/__init__.py
  schoolbot/bot.py
  schoolbot/cogs/events/ready.py
Labels: QA

#32 deploy beta
  schoolbot/cogs/general/help.py
Labels: QA

#53 feat: added meal prerendering ( #36 )
  README.md
  requirements.txt
  schoolbot/cogs/school/meal.py
Labels: feature, to staging

#49 feat: aiomysql
  .github/workflows/python-app-lint.yml
  schoolbot/cogs/events/ready.py
  schoolbot/cogs/general/__init__.py
  schoolbot/cogs/general/help.py
  schoolbot/cogs/general/search.py
  schoolbot/cogs/general/setting.py
  schoolbot/cogs/school/academic_schedule.py
  schoolbot/cogs/school/meal.py
  schoolbot/cogs/school/timetable.py
  schoolbot/db.py
Labels: feature, to staging, wait

#58 neispy 3.0 update corver, resolve conversation
  .github/workflows/python-app-lint.yml
  schoolbot/cogs/events/error.py
  schoolbot/cogs/general/__init__.py
  schoolbot/cogs/general/search.py
  schoolbot/cogs/general/setting.py
  schoolbot/cogs/school/academic_schedule.py
  schoolbot/cogs/school/article.py
  schoolbot/cogs/school/meal.py
  schoolbot/cogs/school/timetable.py
Labels: fix, refactor, style, to staging

#61 deploy beta
  .github/dependabot.yml
  .github/workflows/python-app-lint.yml
  .github/workflows/python-app-test.yml
  README.md
  requirements.txt
  schoolbot/cogs/events/error.py
  schoolbot/cogs/events/ready.py
  schoolbot/cogs/general/__init__.py
  schoolbot/cogs/general/help.py
  schoolbot/cogs/general/search.py
  schoolbot/cogs/general/setting.py
  schoolbot/cogs/school/academic_schedule.py
  schoolbot/cogs/school/article.py
  schoolbot/cogs/school/meal.py
  schoolbot/cogs/school/timetable.py
  schoolbot/db.py
Labels: QA

#28 Update 1.0.0
  .github/CODEOWNERS
  .github/dependabot.yml
  .github/workflows/python-app-lint.yml
  .github/workflows/python-app-test.yml
  README.md
  requirements.txt
  schoolbot/__init__.py
  schoolbot/bot.py
  schoolbot/cogs/events/__init__.py
  schoolbot/cogs/events/error.py
  schoolbot/cogs/events/ready.py
  schoolbot/cogs/general/__init__.py
  schoolbot/cogs/general/help.py
  schoolbot/cogs/general/search.py
  schoolbot/cogs/general/setting.py
  schoolbot/cogs/school/__init__.py
  schoolbot/cogs/school/academic_schedule.py
  schoolbot/cogs/school/article.py
  schoolbot/cogs/school/meal.py
  schoolbot/cogs/school/timetable.py
  schoolbot/db.py
  utils/__init__.py
  utils/kst.py
Labels: release, wait
