Repository callistoteam/schoolbot, pull requests merged in 2020-09, with the labels that each got.

#65 deploy beta
  README.md
  ext/users.sql
Labels: QA

#66 deploy beta
  schoolbot/cogs/general/setting.py
  schoolbot/cogs/school/academic_schedule.py
  schoolbot/cogs/school/meal.py
Labels: QA

#67 Maybe fixed db problem
  schoolbot/cogs/general/setting.py
  schoolbot/cogs/school/academic_schedule.py
  schoolbot/cogs/school/meal.py
  schoolbot/cogs/school/timetable.py
  schoolbot/db.py
Labels: fix

#68 deploy beta
  schoolbot/cogs/school/academic_schedule.py
  schoolbot/cogs/school/meal.py
  schoolbot/cogs/school/timetable.py
  schoolbot/db.py
Labels: QA

#69 fix: receiving wrong argument value
  schoolbot/cogs/school/timetable.py
Labels: fix

#70 deploy beta
  schoolbot/cogs/school/timetable.py
Labels: QA

#72 deploy beta
  schoolbot/cogs/school/timetable.py
Labels: QA

#73 fix: human error
  schoolbot/cogs/school/timetable.py
Labels: fix

#76 deploy beta
  schoolbot/cogs/school/timetable.py
Labels: QA

#85 hotfix deploy beta
  schoolbot/cogs/events/error.py
  schoolbot/cogs/general/setting.py
  schoolbot/cogs/school/article.py
Labels: hotfix

#107 1.3.0 beta deploy
  bot.py
  cogs/article.py
  cogs/meal.py
  cogs/schedule.py
  cogs/setting.py
  cogs/timetable.py
Labels: QA, chore

#110 1.3.1 beta deploy
  bot.py
  cogs/article.py
  cogs/help.py
  cogs/meal.py
  cogs/schedule.py
  cogs/timetable.py
Labels: QA, chore
